# This is a basic workflow to help you get started with Actions
name: Linter

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > .npmrc
          echo "@ncent-holdings:registry=https://npm.pkg.github.com/nCent-Holdings" >> .npmrc
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
      - run: npx tsc
